# Generated by Django 5.2.7 on 2025-11-29 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código/Patrimônio')),
                ('ca', models.CharField(blank=True, max_length=30, verbose_name='Certificado de Aprovação (CA)')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='data_admissao',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ControleEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da entrega')),
                ('data_prevista_devolucao', models.DateTimeField(verbose_name='Data prevista para devolução')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data da devolução')),
                ('status', models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('EM_USO', 'Em uso'), ('FORNECIDO', 'Fornecido'), ('DEVOLVIDO', 'Devolvido'), ('DANIFICADO', 'Danificado'), ('PERDIDO', 'Perdido')], default='EMPRESTADO', max_length=20)),
                ('observacao', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('observacao_devolucao', models.TextField(blank=True, verbose_name='Observação na devolução')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='page_app.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='page_app.equipamento')),
            ],
        ),
    ]
