# Generated by Django 5.2.7 on 2025-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_app', '0002_equipamento_usuariosistema_remove_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(blank=True, choices=[('Auxiliar', 'Auxiliar'), ('Operador de Máquina', 'Operador de Máquina'), ('Eletricista', 'Eletricista'), ('Supervisor', 'Supervisor'), ('Técnico de Segurança', 'Técnico de Segurança'), ('Soldador', 'Soldador'), ('Mecânico', 'Mecânico'), ('Almoxarife', 'Almoxarife'), ('Engenheiro', 'Engenheiro'), ('Inspetor', 'Inspetor')], max_length=100, null=True, verbose_name='Função / Cargo'),
        ),
    ]
